language: php

php:
 - 7.1

services:
  - mysql

before_install:
  - composer global require "hirak/prestissimo:^0.3"

install:
  - composer install

script: tools/scripts/dummy.sh

notifications:
  email: false
