version: "2"

services:
  php:
    image: registry.qajedi.ru:5043/drupal/php7:latest # or registry.qajedi.ru:5043/drupal/php7:latest
    environment:
      PHP_DOCROOT: docroot # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S opensmtpd:25
      PHP_XDEBUG_ENABLED: 0 # Set 1 to enable.
      PHP_XHPROF_ENABLED: 0 # Set 1 to enable.
      PROJECT_ENV_TYPE: dev
    volumes:
      - ../../:/var/www/html
      - ./docker-runtime/settings/:/var/www/site-php/project_name
      - ./php.ini:/etc/php7/conf.d/custom.php.ini
    restart: always

  nginx:
    image: registry.qajedi.ru:5043/drupal/nginx:latest
    environment:
      # replace place holder with comma separated domains.
      NGINX_SERVER_NAME: dev.project_name.qajedi.ru
      NGINX_UPSTREAM_NAME: php
      NGINX_DOCROOT: docroot # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 8 # Allowed: 7, 8.
      # replace examples with domains from NGINX_SERVER_NAME
    ports:
      - "80:80"
    volumes_from:
      - php
    restart: always

  mailhog:
    image: registry.qajedi.ru:5043/mailhog:latest
    ports:
      - "8080:8025"

  opensmtpd:
    image: registry.qajedi.ru:5043/opensmtpd:latest
    restart: always

  mariadb:
    image: registry.qajedi.ru:5043/mariadb:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: 'project_name' # change dbname
      MYSQL_USER: 'project_name' #change db user
      MYSQL_PASSWORD: 'Ac1EgReh' #change password to db
    volumes:
      - ./docker-runtime/mysql:/var/lib/mysql  #change placeholder to dir where to store mysql data
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
